Repository issue-tracker/issue-tracker-server, pull requests merged in 2022-09, with the labels that each got.

#57 [Feat] 이슈 변경 이력 조회 기능 추가
  src/main/java/com/ahoo/issuetrackerserver/common/exception/ErrorType.java
  src/main/java/com/ahoo/issuetrackerserver/issue/application/IssueService.java
  src/main/java/com/ahoo/issuetrackerserver/issue/application/aspect/IssueHistoryAspect.java
  src/main/java/com/ahoo/issuetrackerserver/issue/application/aspect/IssueHistoryLogging.java
  src/main/java/com/ahoo/issuetrackerserver/issue/domain/Issue.java
  src/main/java/com/ahoo/issuetrackerserver/issue/domain/IssueHistory.java
  src/main/java/com/ahoo/issuetrackerserver/issue/domain/IssueUpdateAction.java
  src/main/java/com/ahoo/issuetrackerserver/issue/infrastructure/IssueHistoryRepository.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/IssueController.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/dto/IssueHistoryResponse.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/dto/IssueResponse.java
Labels: enhancement

#61 [Fix] 발견된 API 에러 처리
  src/main/java/com/ahoo/issuetrackerserver/issue/application/IssueQueryParser.java
  src/main/java/com/ahoo/issuetrackerserver/label/application/LabelService.java
  src/main/java/com/ahoo/issuetrackerserver/milestone/application/MilestoneService.java
  src/main/java/com/ahoo/issuetrackerserver/milestone/domain/Milestone.java
Labels: fix

#63 [Feat] 리액션 이모지 전체 조회 API 구현
  src/main/java/com/ahoo/issuetrackerserver/issue/application/IssueService.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/IssueController.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/dto/EmojiResponse.java
Labels: enhancement

#65 [Fix] 이슈 API 버그 수정
  src/main/java/com/ahoo/issuetrackerserver/issue/domain/Emoji.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/dto/IssueResponse.java
  src/main/resources/sql/data.sql
Labels: fix

#68 🚀 대망의 세 번째 배포
  README.md
  src/main/java/com/ahoo/issuetrackerserver/common/exception/ErrorType.java
  src/main/java/com/ahoo/issuetrackerserver/issue/application/IssueQueryParser.java
  src/main/java/com/ahoo/issuetrackerserver/issue/application/IssueService.java
  src/main/java/com/ahoo/issuetrackerserver/issue/application/aspect/IssueHistoryAspect.java
  src/main/java/com/ahoo/issuetrackerserver/issue/application/aspect/IssueHistoryLogging.java
  src/main/java/com/ahoo/issuetrackerserver/issue/domain/Emoji.java
  src/main/java/com/ahoo/issuetrackerserver/issue/domain/Issue.java
  src/main/java/com/ahoo/issuetrackerserver/issue/domain/IssueHistory.java
  src/main/java/com/ahoo/issuetrackerserver/issue/domain/IssueUpdateAction.java
  src/main/java/com/ahoo/issuetrackerserver/issue/infrastructure/IssueHistoryRepository.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/IssueController.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/dto/EmojiResponse.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/dto/IssueHistoryResponse.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/dto/IssueResponse.java
  src/main/java/com/ahoo/issuetrackerserver/label/application/LabelService.java
  src/main/java/com/ahoo/issuetrackerserver/member/application/MemberService.java
  src/main/java/com/ahoo/issuetrackerserver/member/presentation/MemberController.java
  src/main/java/com/ahoo/issuetrackerserver/milestone/application/MilestoneService.java
  src/main/java/com/ahoo/issuetrackerserver/milestone/domain/Milestone.java
  src/main/resources/sql/data.sql
Labels: enhancement, 🚀 deploy

#70 [Feat] 누락된 이슈 코멘트 관련 요구사항 반영
  src/main/java/com/ahoo/issuetrackerserver/common/exception/ErrorType.java
  src/main/java/com/ahoo/issuetrackerserver/issue/application/IssueService.java
  src/main/java/com/ahoo/issuetrackerserver/issue/domain/Issue.java
  src/main/resources/sql/data.sql
Labels: enhancement

#72 [Fix] 이슈등록 API 버그 수정
  src/main/java/com/ahoo/issuetrackerserver/issue/application/IssueService.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/dto/IssueResponse.java
Labels: bug

#74 [Fix] 이슈 필터링 조회 페이징 오류 개선
  src/main/java/com/ahoo/issuetrackerserver/issue/application/IssueService.java
  src/main/java/com/ahoo/issuetrackerserver/issue/infrastructure/IssueRepositoryImpl.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/dto/IssuesResponse.java
Labels: bug

#76 [Fix] 발견된 결함 수정
  src/main/java/com/ahoo/issuetrackerserver/auth/presentation/AuthController.java
  src/main/java/com/ahoo/issuetrackerserver/issue/application/IssueService.java
  src/main/java/com/ahoo/issuetrackerserver/issue/application/aspect/IssueHistoryAspect.java
  src/main/java/com/ahoo/issuetrackerserver/issue/infrastructure/IssueHistoryRepository.java
  src/main/java/com/ahoo/issuetrackerserver/issue/infrastructure/IssueRepository.java
  src/main/java/com/ahoo/issuetrackerserver/issue/infrastructure/IssueRepositoryCustom.java
  src/main/java/com/ahoo/issuetrackerserver/issue/infrastructure/IssueRepositoryImpl.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/IssueController.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/dto/IssueSearchFilter.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/dto/IssuesResponse.java
  src/main/java/com/ahoo/issuetrackerserver/member/presentation/MemberController.java
Labels: bug

#78 [Fix] 발견된 결함 및 요청사항 처리
  src/main/java/com/ahoo/issuetrackerserver/common/exception/ErrorType.java
  src/main/java/com/ahoo/issuetrackerserver/issue/application/IssueService.java
  src/main/java/com/ahoo/issuetrackerserver/issue/domain/IssueHistory.java
  src/main/java/com/ahoo/issuetrackerserver/issue/infrastructure/IssueHistoryRepository.java
  src/main/java/com/ahoo/issuetrackerserver/issue/infrastructure/IssueRepositoryImpl.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/dto/IssueHistoryMilestone.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/dto/IssueHistoryResponse.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/dto/IssueResponse.java
  src/main/java/com/ahoo/issuetrackerserver/milestone/application/MilestoneService.java
  src/main/java/com/ahoo/issuetrackerserver/milestone/infrastructure/MilestoneRepository.java
Labels: enhancement, fix
