Repository issue-tracker/issue-tracker-server, pull requests merged in 2022-08, with the labels that each got.

#26 [Feat] 로그인 검증 및 회원아이디 매핑을 위한 ArgumentResolver 구현
  src/main/java/com/ahoo/issuetrackerserver/auth/AuthController.java
  src/main/java/com/ahoo/issuetrackerserver/auth/JwtService.java
  src/main/java/com/ahoo/issuetrackerserver/auth/SignInAspect.java
  src/main/java/com/ahoo/issuetrackerserver/auth/SignInMemberId.java
  src/main/java/com/ahoo/issuetrackerserver/auth/SignInMemberIdArgumentResolver.java
  src/main/java/com/ahoo/issuetrackerserver/config/ArgumentResolverConfig.java
Labels: enhancement

#28 [Feat] Auth 회원가입 추가 요구사항 반영 및 리팩토링
  src/main/java/com/ahoo/issuetrackerserver/auth/AuthController.java
  src/main/java/com/ahoo/issuetrackerserver/member/MemberController.java
Labels: enhancement

#29 [Feat] 만료된 AccessToken 갱신 기능 구현
  src/main/java/com/ahoo/issuetrackerserver/auth/AccessToken.java
  src/main/java/com/ahoo/issuetrackerserver/auth/AuthController.java
  src/main/java/com/ahoo/issuetrackerserver/auth/JwtService.java
  src/main/java/com/ahoo/issuetrackerserver/auth/JwtToken.java
  src/main/java/com/ahoo/issuetrackerserver/auth/RefreshToken.java
  src/main/java/com/ahoo/issuetrackerserver/auth/SignInMemberIdArgumentResolver.java
  src/main/java/com/ahoo/issuetrackerserver/exception/GlobalExceptionHandler.java
  src/main/java/com/ahoo/issuetrackerserver/member/MemberController.java
  src/main/java/com/ahoo/issuetrackerserver/member/MemberService.java
Labels: enhancement

#30 [Feat] CORS 처리를 위한 설정 추가
  src/main/java/com/ahoo/issuetrackerserver/config/CorsConfig.java
Labels: enhancement

#31 [Fix] 쿠키 허용되는 경로 수정
  src/main/java/com/ahoo/issuetrackerserver/auth/AccessToken.java
  src/main/java/com/ahoo/issuetrackerserver/auth/AuthController.java
  src/main/java/com/ahoo/issuetrackerserver/auth/RefreshToken.java
Labels: enhancement

#34 [Fix] 프론트 요청 사항 적용 및 로그아웃 API 구현
  src/main/java/com/ahoo/issuetrackerserver/auth/AccessToken.java
  src/main/java/com/ahoo/issuetrackerserver/auth/AuthController.java
  src/main/java/com/ahoo/issuetrackerserver/auth/AuthService.java
  src/main/java/com/ahoo/issuetrackerserver/auth/RefreshToken.java
  src/main/java/com/ahoo/issuetrackerserver/auth/SignInMemberIdArgumentResolver.java
  src/main/java/com/ahoo/issuetrackerserver/auth/dto/AuthResponse.java
  src/main/java/com/ahoo/issuetrackerserver/auth/jwt/JwtGenerator.java
  src/main/java/com/ahoo/issuetrackerserver/exception/GlobalExceptionHandler.java
  src/main/java/com/ahoo/issuetrackerserver/member/Member.java
  src/main/java/com/ahoo/issuetrackerserver/member/MemberController.java
  src/main/java/com/ahoo/issuetrackerserver/member/MemberRepository.java
  src/main/java/com/ahoo/issuetrackerserver/member/MemberService.java
  src/main/java/com/ahoo/issuetrackerserver/member/dto/GeneralMemberCreateRequest.java
  src/main/java/com/ahoo/issuetrackerserver/member/dto/SignResponse.java
  src/main/resources/sql/data.sql
  src/test/java/com/ahoo/issuetrackerserver/member/MemberServiceTest.java
Labels: enhancement, fix

#41 [Feat] 마일스톤 도메인 기능 개발
  src/main/java/com/ahoo/issuetrackerserver/common/exception/ErrorMessage.java
  src/main/java/com/ahoo/issuetrackerserver/milestone/application/MilestoneService.java
  src/main/java/com/ahoo/issuetrackerserver/milestone/domain/Milestone.java
  src/main/java/com/ahoo/issuetrackerserver/milestone/infrastructure/MilestoneRepository.java
  src/main/java/com/ahoo/issuetrackerserver/milestone/presentation/MilestoneController.java
  src/main/java/com/ahoo/issuetrackerserver/milestone/presentation/dto/AddMilestoneRequest.java
  src/main/java/com/ahoo/issuetrackerserver/milestone/presentation/dto/MilestoneResponse.java
  src/main/java/com/ahoo/issuetrackerserver/milestone/presentation/dto/MilestonesResponse.java
  src/main/java/com/ahoo/issuetrackerserver/milestone/presentation/dto/UpdateMilestoneRequest.java
  src/main/resources/sql/data.sql
Labels: enhancement

#40 [Feat] 라벨 도메인 기능 구현
  src/main/java/com/ahoo/issuetrackerserver/common/exception/DuplicatedLabelTitleException.java
  src/main/java/com/ahoo/issuetrackerserver/common/exception/ErrorMessage.java
  src/main/java/com/ahoo/issuetrackerserver/common/exception/GlobalExceptionHandler.java
  src/main/java/com/ahoo/issuetrackerserver/label/application/LabelService.java
  src/main/java/com/ahoo/issuetrackerserver/label/domain/Label.java
  src/main/java/com/ahoo/issuetrackerserver/label/domain/TextColor.java
  src/main/java/com/ahoo/issuetrackerserver/label/infrastructure/LabelRepository.java
  src/main/java/com/ahoo/issuetrackerserver/label/presentation/LabelController.java
  src/main/java/com/ahoo/issuetrackerserver/label/presentation/dto/LabelCreateRequest.java
  src/main/java/com/ahoo/issuetrackerserver/label/presentation/dto/LabelResponse.java
  src/main/java/com/ahoo/issuetrackerserver/label/presentation/dto/LabelUpdateRequest.java
Labels: enhancement

#43 [Feat] 이슈 도메인 기능 구현
  build.gradle
  src/main/java/com/ahoo/issuetrackerserver/auth/presentation/AuthController.java
  src/main/java/com/ahoo/issuetrackerserver/common/exception/DuplicateMemberException.java
  src/main/java/com/ahoo/issuetrackerserver/common/exception/DuplicatedMemberException.java
  src/main/java/com/ahoo/issuetrackerserver/common/exception/DuplicatedReactionException.java
  src/main/java/com/ahoo/issuetrackerserver/common/exception/ErrorMessage.java
  src/main/java/com/ahoo/issuetrackerserver/common/exception/GlobalExceptionHandler.java
  src/main/java/com/ahoo/issuetrackerserver/issue/application/IssueService.java
  src/main/java/com/ahoo/issuetrackerserver/issue/domain/Comment.java
  src/main/java/com/ahoo/issuetrackerserver/issue/domain/Emoji.java
  src/main/java/com/ahoo/issuetrackerserver/issue/domain/Issue.java
  src/main/java/com/ahoo/issuetrackerserver/issue/domain/IssueAssignee.java
  src/main/java/com/ahoo/issuetrackerserver/issue/domain/IssueLabel.java
  src/main/java/com/ahoo/issuetrackerserver/issue/domain/Reaction.java
  src/main/java/com/ahoo/issuetrackerserver/issue/infrastructure/CommentRepository.java
  src/main/java/com/ahoo/issuetrackerserver/issue/infrastructure/IssueCustomRepository.java
  src/main/java/com/ahoo/issuetrackerserver/issue/infrastructure/IssueImplRepository.java
  src/main/java/com/ahoo/issuetrackerserver/issue/infrastructure/IssueRepository.java
  src/main/java/com/ahoo/issuetrackerserver/issue/infrastructure/ReactionRepository.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/IssueController.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/dto/CommentResponse.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/dto/IssueAssigneesResponse.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/dto/IssueCommentReactionRequest.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/dto/IssueCommentReactionResponse.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/dto/IssueCommentReactorResponse.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/dto/IssueCommentRequest.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/dto/IssueCreateRequest.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/dto/IssueLabelsResponse.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/dto/IssueResponse.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/dto/IssueStatusUpdateRequest.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/dto/IssueTitleUpdateRequest.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/dto/IssuesResponse.java
  src/main/java/com/ahoo/issuetrackerserver/label/domain/Label.java
  src/main/java/com/ahoo/issuetrackerserver/member/application/MemberService.java
  src/main/java/com/ahoo/issuetrackerserver/milestone/domain/Milestone.java
  src/main/resources/application-dev.yml
  src/main/resources/sql/data.sql
  src/test/java/com/ahoo/issuetrackerserver/member/MemberServiceTest.java
Labels: enhancement

#44 [Refactor] 전체적인 코드 리팩토링
  src/main/java/com/ahoo/issuetrackerserver/auth/application/AuthService.java
  src/main/java/com/ahoo/issuetrackerserver/auth/application/JwtService.java
  src/main/java/com/ahoo/issuetrackerserver/auth/presentation/AuthController.java
  src/main/java/com/ahoo/issuetrackerserver/common/argumentresolver/SignInMemberIdArgumentResolver.java
  src/main/java/com/ahoo/issuetrackerserver/common/exception/ApplicationException.java
  src/main/java/com/ahoo/issuetrackerserver/common/exception/DuplicatedLabelTitleException.java
  src/main/java/com/ahoo/issuetrackerserver/common/exception/DuplicatedMemberException.java
  src/main/java/com/ahoo/issuetrackerserver/common/exception/DuplicatedReactionException.java
  src/main/java/com/ahoo/issuetrackerserver/common/exception/ErrorMessage.java
  src/main/java/com/ahoo/issuetrackerserver/common/exception/ErrorResponse.java
  src/main/java/com/ahoo/issuetrackerserver/common/exception/ErrorType.java
  src/main/java/com/ahoo/issuetrackerserver/common/exception/EssentialFieldDisagreeException.java
  src/main/java/com/ahoo/issuetrackerserver/common/exception/GlobalExceptionHandler.java
  src/main/java/com/ahoo/issuetrackerserver/common/exception/IllegalAuthProviderTypeException.java
  src/main/java/com/ahoo/issuetrackerserver/common/exception/UnAuthorizedException.java
  src/main/java/com/ahoo/issuetrackerserver/issue/application/IssueService.java
  src/main/java/com/ahoo/issuetrackerserver/issue/domain/Comment.java
  src/main/java/com/ahoo/issuetrackerserver/issue/domain/Issue.java
  src/main/java/com/ahoo/issuetrackerserver/issue/domain/Reaction.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/IssueController.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/dto/IssueCommentRequest.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/dto/IssueCreateRequest.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/dto/IssueTitleUpdateRequest.java
  src/main/java/com/ahoo/issuetrackerserver/label/application/LabelService.java
  src/main/java/com/ahoo/issuetrackerserver/label/domain/Label.java
  src/main/java/com/ahoo/issuetrackerserver/label/presentation/dto/LabelCreateRequest.java
  src/main/java/com/ahoo/issuetrackerserver/label/presentation/dto/LabelUpdateRequest.java
  src/main/java/com/ahoo/issuetrackerserver/member/application/MemberService.java
  src/main/java/com/ahoo/issuetrackerserver/milestone/application/MilestoneService.java
  src/main/java/com/ahoo/issuetrackerserver/milestone/domain/Milestone.java
  src/main/java/com/ahoo/issuetrackerserver/milestone/presentation/MilestoneController.java
  src/main/java/com/ahoo/issuetrackerserver/milestone/presentation/dto/AddMilestoneRequest.java
  src/main/java/com/ahoo/issuetrackerserver/milestone/presentation/dto/MilestoneCreateRequest.java
  src/main/java/com/ahoo/issuetrackerserver/milestone/presentation/dto/MilestoneUpdateRequest.java
  src/test/java/com/ahoo/issuetrackerserver/member/MemberServiceTest.java
Labels: refactor

#47 [Feat] 이슈 필터링 조회 기능 구현
  src/main/java/com/ahoo/issuetrackerserver/config/CorsConfig.java
  src/main/java/com/ahoo/issuetrackerserver/config/QuerydslConfig.java
  src/main/java/com/ahoo/issuetrackerserver/issue/application/IssueQueryParser.java
  src/main/java/com/ahoo/issuetrackerserver/issue/application/IssueService.java
  src/main/java/com/ahoo/issuetrackerserver/issue/infrastructure/IssueCustomRepository.java
  src/main/java/com/ahoo/issuetrackerserver/issue/infrastructure/IssueImplRepository.java
  src/main/java/com/ahoo/issuetrackerserver/issue/infrastructure/IssueRepository.java
  src/main/java/com/ahoo/issuetrackerserver/issue/infrastructure/IssueRepositoryCustom.java
  src/main/java/com/ahoo/issuetrackerserver/issue/infrastructure/IssueRepositoryImpl.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/IssueController.java
  src/main/java/com/ahoo/issuetrackerserver/issue/presentation/dto/IssueSearchFilter.java
Labels: enhancement

#49 [Feat] GitHub Action 스크립트 추가
  .github/workflows/gradle.yml
Labels: enhancement

#51 [Feat] AWS S3 이미지 업로드 기능 구현
  build.gradle
  src/main/java/com/ahoo/issuetrackerserver/common/exception/ErrorType.java
  src/main/java/com/ahoo/issuetrackerserver/upload/application/S3UploadService.java
  src/main/java/com/ahoo/issuetrackerserver/upload/domain/S3Component.java
  src/main/java/com/ahoo/issuetrackerserver/upload/presentation/S3UploadController.java
  src/main/resources/application-dev.yml
Labels: enhancement

#54 [Feat] 마일스톤 조회 - 연관된 이슈 진척도 추가
  src/main/java/com/ahoo/issuetrackerserver/issue/infrastructure/IssueRepository.java
  src/main/java/com/ahoo/issuetrackerserver/milestone/application/MilestoneService.java
  src/main/java/com/ahoo/issuetrackerserver/milestone/infrastructure/MilestoneRepository.java
  src/main/java/com/ahoo/issuetrackerserver/milestone/presentation/dto/MilestoneResponse.java
Labels: enhancement

#55 🚀 대망의 두 번째 배포
  build.gradle
  src/main/java/com/ahoo/issuetrackerserver/common/exception/ErrorType.java
  src/main/java/com/ahoo/issuetrackerserver/issue/infrastructure/IssueRepository.java
  src/main/java/com/ahoo/issuetrackerserver/milestone/application/MilestoneService.java
  src/main/java/com/ahoo/issuetrackerserver/milestone/infrastructure/MilestoneRepository.java
  src/main/java/com/ahoo/issuetrackerserver/milestone/presentation/dto/MilestoneResponse.java
  src/main/java/com/ahoo/issuetrackerserver/upload/application/S3UploadService.java
  src/main/java/com/ahoo/issuetrackerserver/upload/domain/S3Component.java
  src/main/java/com/ahoo/issuetrackerserver/upload/presentation/S3UploadController.java
  src/main/resources/application-dev.yml
Labels: 🚀 deploy
